if(AIF_BUILD_PLUGINS AND AIF_TEST_RUNTIME)
 add_executable(aif_convolution_filter_tests filter_tests.cpp)
 target_include_directories(aif_convolution_filter_tests PRIVATE "${AIF_AVISYNTH_INCLUDE_DIR}" "${PROJECT_SOURCE_DIR}/src/convolution/include")
 target_link_libraries(aif_convolution_filter_tests PRIVATE ${CMAKE_DL_LIBS})
 aif_target_defaults(aif_convolution_filter_tests)
 add_dependencies(aif_convolution_filter_tests aif_convolution_plugin)
 add_test(NAME convolution.filters COMMAND aif_convolution_filter_tests "${AIF_TEST_RUNTIME}" "$<TARGET_FILE:aif_convolution_plugin>")
endif()

add_executable(aif_convolution_kernel_tests kernel_tests.cpp)
target_link_libraries(aif_convolution_kernel_tests PRIVATE AvsFilters::ConvolutionKernels)
aif_target_defaults(aif_convolution_kernel_tests)
add_test(NAME convolution.kernels COMMAND aif_convolution_kernel_tests)
add_executable(aif_convolution_c_consumer c_consumer.c)
target_link_libraries(aif_convolution_c_consumer PRIVATE AvsFilters::ConvolutionKernels)
add_test(NAME convolution.c_consumer COMMAND aif_convolution_c_consumer)
