if(AIF_BUILD_PLUGINS AND AIF_TEST_RUNTIME)
 add_executable(aif_histogram_filter_tests filter_tests.cpp)
 target_include_directories(aif_histogram_filter_tests PRIVATE "${AIF_AVISYNTH_INCLUDE_DIR}")
 target_link_libraries(aif_histogram_filter_tests PRIVATE ${CMAKE_DL_LIBS})
 aif_target_defaults(aif_histogram_filter_tests)
 add_dependencies(aif_histogram_filter_tests aif_histogram_plugin)
 add_test(NAME histogram.filters COMMAND aif_histogram_filter_tests "${AIF_TEST_RUNTIME}" "$<TARGET_FILE:aif_histogram_plugin>")
endif()
