# Reuse the composite module already supplied by a parent build, or require an
# explicit source checkout for standalone builds. Never download dependencies.
set(AIF_COMPOSITE_SOURCE_DIR "" CACHE PATH "AviSynthComposite source checkout")
if(NOT TARGET AviSynth::Composite)
  # Composite's own dependency check uses the unnamespaced target.
  if(NOT TARGET hwy AND TARGET hwy::hwy)
    get_target_property(aif_hwy_original hwy::hwy ALIASED_TARGET)
    if(aif_hwy_original)
      add_library(hwy ALIAS ${aif_hwy_original})
    else()
      add_library(hwy ALIAS hwy::hwy)
    endif()
  endif()
  if(NOT EXISTS "${AIF_COMPOSITE_SOURCE_DIR}/include/composite/dispatch.h")
    message(FATAL_ERROR "Provide AviSynth::Composite or set AIF_COMPOSITE_SOURCE_DIR")
  endif()
  set(CP_BUILD_TESTS OFF)
  set(CP_BUILD_BENCHMARKS OFF)
  set(CP_SCALAR_ONLY ${AIF_SCALAR_ONLY})
  add_subdirectory("${AIF_COMPOSITE_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/composite" EXCLUDE_FROM_ALL)
  if(NOT AIF_SCALAR_ONLY)
    target_compile_definitions(Composite PRIVATE HWY_COMPILE_ALL_ATTAINABLE HWY_WANT_SSE2=1 HWY_WANT_SSSE3=1 HWY_WANT_SSE4=1 HWY_WANT_AVX3_ZEN4=1)
  endif()
  if(AIF_ENABLE_INSTALL)
    set_target_properties(Composite PROPERTIES EXPORT_NAME Composite)
    target_include_directories(Composite PUBLIC $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
    install(TARGETS Composite EXPORT AviSynthInternalFiltersTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
    install(DIRECTORY "${AIF_COMPOSITE_SOURCE_DIR}/include/composite" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  endif()
endif()
