# Reuse the conversion module already supplied by a parent build, or require an
# explicit source checkout for standalone builds. Never download dependencies.
set(AIF_VIDEO_CONVERT_SOURCE_DIR "" CACHE PATH "AviSynthConvertVideo source checkout")
if(NOT TARGET AviSynth::ConvertVideo)
  # ConvertVideo's own dependency check uses the unnamespaced target.
  if(NOT TARGET hwy AND TARGET hwy::hwy)
    get_target_property(aif_hwy_original hwy::hwy ALIASED_TARGET)
    if(aif_hwy_original)
      add_library(hwy ALIAS ${aif_hwy_original})
    else()
      add_library(hwy ALIAS hwy::hwy)
    endif()
  endif()
  if(NOT EXISTS "${AIF_VIDEO_CONVERT_SOURCE_DIR}/include/video_convert/matrix.h")
    message(FATAL_ERROR "Provide AviSynth::ConvertVideo or set AIF_VIDEO_CONVERT_SOURCE_DIR")
  endif()
  set(VC_BUILD_TESTS OFF)
  set(VC_BUILD_BENCHMARKS OFF)
  set(VC_SCALAR_ONLY ${AIF_SCALAR_ONLY})
  add_subdirectory("${AIF_VIDEO_CONVERT_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/video_convert" EXCLUDE_FROM_ALL)
  if(NOT AIF_SCALAR_ONLY)
    target_compile_definitions(VideoConvert PRIVATE HWY_WANT_SSE2=1 HWY_WANT_SSSE3=1 HWY_WANT_SSE4=1 HWY_WANT_AVX3_ZEN4=1 HWY_COMPILE_ALL_ATTAINABLE)
  endif()
  if(AIF_ENABLE_INSTALL)
    set_target_properties(VideoConvert PROPERTIES EXPORT_NAME VideoConvert)
    target_include_directories(VideoConvert PUBLIC $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
    install(TARGETS VideoConvert EXPORT AviSynthInternalFiltersTargets ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
    install(DIRECTORY "${AIF_VIDEO_CONVERT_SOURCE_DIR}/include/video_convert" DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  endif()
endif()
