if(AIF_BUILD_PLUGINS AND AIF_TEST_RUNTIME)
 add_executable(aif_overlay_filter_tests filter_tests.cpp)
 target_include_directories(aif_overlay_filter_tests PRIVATE "${AIF_AVISYNTH_INCLUDE_DIR}")
 target_link_libraries(aif_overlay_filter_tests PRIVATE ${CMAKE_DL_LIBS})
 aif_target_defaults(aif_overlay_filter_tests)
 add_dependencies(aif_overlay_filter_tests aif_overlay_plugin)
 add_test(NAME overlay.filters COMMAND aif_overlay_filter_tests "${AIF_TEST_RUNTIME}" "$<TARGET_FILE:aif_overlay_plugin>")
endif()

if(AIF_BUILD_FILTERS)
 add_executable(aif_overlay_kernel_tests kernel_tests.cpp)
 target_include_directories(aif_overlay_kernel_tests PRIVATE "${PROJECT_SOURCE_DIR}/src/overlay")
 target_link_libraries(aif_overlay_kernel_tests PRIVATE AvsFilters::OverlayFilters)
 aif_target_defaults(aif_overlay_kernel_tests)
 add_test(NAME overlay.kernels COMMAND aif_overlay_kernel_tests)
endif()
